name: seamlink
description: Seamlessly share notes and links!

publish_to: 'none' 

version: 3.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.3
  animate_do:
  supabase:
  google_fonts:
  substring_highlight:
  url_launcher:
  animations:
  flutter_staggered_grid_view: ^0.4.0
  flutter_spinkit:
  http:
  html:
  auto_size_text_field: ^2.2.3
  auto_size_text: ^3.0.0-nullsafety.0
  receive_sharing_intent: ^1.4.5
  line_icons: ^2.0.1  
  shared_preferences:
  flutter_staggered_animations:
    git:
      url: https://github.com/Vidhanth/flutter_staggered_animations.git
      ref: master
  flutter_launcher_icons:
  fade_shimmer: ^2.2.0
  octo_image: ^2.0.0
  flutter_svg:
  share_plus: ^8.0.2
  intl: ^0.19.0
  flutter_dotenv:
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: e48abe7c3e9ebfe0b81622167c5201d4e783bb81
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/images/ic_launcher.png"
  adaptive_icon_foreground: "assets/images/ic_launcher_fg.png"
  adaptive_icon_background: "#ffffff"

flutter:
  
  assets:
    - assets/images/
    - .env

  uses-material-design: true
